### PR TITLE
Bump dependencies to allow usage with rails 5.1

### PR DESCRIPTION
**Pull request by mcolyer**
I wasn't entirely sure how to keep compatibility with the current version ranges while also allowing newer versions of the dependencies to be used but I figured it's a good starting spot.

### CODE REVIEW

**Comment by esbanarango** [comment]
Thank you @mcolyer. We also need to update `Gemfile.lock` did you run `bundle install`? also, did the tests passed locally for you?

**Comment by fastjames** [comment]
I tried this and got hung up on some failing specs. As far as I can tell, the failure happens because `rest-client` now handles HTTP request bodies as `StringIO` and closes the handle on completion. When the spec tries to read the body from `FakeWeb.last_request` it's already nil.

**Comment by fastjames** [comment]
@mcolyer I hope you don't mind, but I opened a similar PR because I wasn't sure how to offer changes on this one: https://github.com/esbanarango/zapier-REST-hooks/pull/4

I tested my PR with Rails 4.2.10 and 5.1.x and the specs pass in both cases.

Things I don't have time to fix:

1. `spec/dummy` is committed. I think it would be more conventional to gitignore this and have it generated by a rake task. This would have kept `application.rb` up to date.
2. `Gemfile.lock` is committed. I think this means we could not modify the CI files to test in multiple versions of Rails, which would be a great addition.

I should probably file separate issues on those.

Thanks to @esbanarango for putting this gem out there, it was pretty easy to work on.

**Comment by mcolyer** [comment]
Closing in favor of #4

**Pull request closed without merging**
